services:
  - type: web
    name: health-backend
    env: node
    plan: free
    buildCommand: npm run install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: FORCE_SQLITE
        value: true
      - key: NODE_ENV
        value: production
